services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-personal_web}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-winpaing123}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./tables query/create_tables.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Node.js Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs_app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PORT: ${APP_PORT:-5000}
      NODE_ENV: ${NODE_ENV:-development}
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-winpaing123}@postgres:5432/${POSTGRES_DB:-personal_web}
    ports:
      - "${APP_PORT:-5000}:5000"
    volumes:
      - ./uploads:/usr/src/app/uploads

volumes:
  postgres_data:

# services:
#   # PostgreSQL Database Service
#   postgres:
#     image: postgres:15-alpine
#     container_name: postgres_db
#     restart: unless-stopped
#     environment:
#       POSTGRES_DB: ${POSTGRES_DB:-Personal Web}
#       POSTGRES_USER: ${POSTGRES_USER:-postgres}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-winpaing123}
#     ports:
#       - "5435:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres"]
#       interval: 5s
#       timeout: 5s
#       retries: 5

#   # Node.js Application Service
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: nodejs_app
#     restart: unless-stopped
#     depends_on:
#       postgres:
#         condition: service_healthy
#     environment:
#       PORT: ${APP_PORT:-5000}
#       NODE_ENV: ${NODE_ENV:-development}
#       DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-winpaing123}@postgres:5432/${POSTGRES_DB:-Personal%20Web}
#     ports:
#       - "${APP_PORT:-5000}:5000"

# volumes:
#   postgres_data:
